spring:
  application:
    name: GControl-server-registry-service
  profiles:
    active: stag

server:
  port: 8761
eureka:
  instance:
    hostname: https://192.168.1.37
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    eviction-interval-timer-in-ms: 1000


    
